import sys

from toad.settings import SchemaDict

SCHEMA: list[SchemaDict] = [
    {
        "key": "ui",
        "title": "User interface settings",
        "help": "The following settings allow you to customize the look and feel of the User Interface.",
        "type": "object",
        "fields": [
            {
                "key": "theme",
                "title": "Theme",
                "help": "One of the builtin Textual themes.",
                "type": "choices",
                "default": "iris",
                "choices": [
                    "iris",
                    "atom-one-dark",
                    "atom-one-light",
                    "catppuccin-latte",
                    "catppuccin-mocha",
                    "dracula",
                    "flexoki",
                    "gruvbox",
                    "monokai",
                    "nord",
                    "solarized-light",
                    "solarized-dark",
                    "textual-dark",
                    "textual-light",
                    "tokyo-night",
                    "rose-pine",
                    "rose-pine-moon",
                    "rose-pine-dawn",
                ],
            },
            {
                "key": "prompt_message",
                "title": "Prompt message",
                "help": "Text shown as placeholder in prompt text area",
                "type": "string",
                "default": "Como posso ajudar hoje?",
            },
            {
                "key": "compact-input",
                "title": "Compact text input?",
                "help": "Remove border and margin around the text area for additional space",
                "type": "boolean",
                "default": False,
            },
            {
                "key": "sessions-bar",
                "title": "Show sessions bar?",
                "help": "When to show the sessions bar (tabs at top of screen).",
                "type": "choices",
                "default": "always",
                "choices": [
                    ("Always", "always"),
                    ("When there are multiple sessions", "multiple"),
                    ("Never", "never"),
                ],
            },
            {
                "key": "footer",
                "title": "Enable footer?",
                "help": "Disable the footer if you want additional room.",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "info-bar",
                "title": "Enable info bar?",
                "help": "The info bar is the text below the prompt text area. Disable for more space.",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "status-line",
                "title": "Show status line in the info bar?",
                "help": "The status line shows tokens and cost (not available in all agents).",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "agent-title",
                "title": "Show agent title the info bar?",
                "help": "Disable for a little extras space.",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "column",
                "title": "Enable column?",
                "help": "Enable for a fixed column size. Disable to use the full screen width.",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "column-width",
                "title": "Width of the column",
                "help": "Width of the column if enabled. Minimum 40 characters.",
                "type": "integer",
                "default": 100,
                "validate": [{"type": "minimum", "value": 40}],
            },
            {
                "key": "scrollbar",
                "title": "Scrollbar size",
                "type": "choices",
                "default": "normal",
                "choices": [
                    ("Normal", "normal"),
                    ("Thin", "thin"),
                    ("Hidden", "hidden"),
                ],
            },
            {
                "key": "throbber",
                "title": "Thinking animation",
                "help": "Animation to show while waiting for the agent to respond",
                "type": "choices",
                "default": "quotes",
                "choices": [
                    ("Pulse", "pulse"),
                    ("Quotes", "quotes"),
                ],
            },
            {
                "key": "flash_duration",
                "title": "Flash duration",
                "help": "Default duration of flash messages (in seconds)",
                "type": "number",
                "default": 3.0,
                "validate": [{"type": "minimum", "value": 0.5}],
            },
            {
                "key": "auto_copy",
                "title": "Automatic copy",
                "help": "Automatically copy text on selection?\nDoesn't apply to text areas (use ctrl+c to copy).",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "prune_low_mark",
                "title": "Target lines",
                "help": "Keep at least this many number of lines of conversation (minimum 100).",
                "type": "integer",
                "default": 1500,
                "validate": [{"type": "minimum", "value": 100}],
            },
            {
                "key": "prune_excess",
                "title": "Additional lines",
                "help": "Start removing lines when the conversation has this number of lines more than the target (see 'Target lines').",
                "type": "integer",
                "default": 1000,
                "validate": [{"type": "minimum", "value": 0}],
            },
        ],
    },
    {
        "key": "notifications",
        "title": "Notification (toasts) settings",
        "help": "Customize how Toad displays notifications",
        "type": "object",
        "fields": [
            {
                "key": "system",
                "title": "Show Toad notifications on your desktop?",
                "type": "choices",
                "default": "blur",
                "choices": [
                    ("Never", "never"),
                    ("When app is not focused", "blur"),
                    ("Always", "always"),
                ],
            },
            {
                "key": "blink_title",
                "title": "Blink terminal title when input is required?",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "enable_sounds",
                "title": "Allow sound in notifications?",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "turn_over",
                "title": "Desktop notification when agent has finished?",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "hide_low_severity",
                "title": "Limit desktop notifications to warning and errors?",
                "type": "boolean",
                "default": True,
            },
        ],
    },
    {
        "key": "sidebar",
        "title": "Sidebar settings",
        "help": "Customize how the sidebar is displayed.",
        "type": "object",
        "fields": [
            {
                "key": "hide",
                "title": "Hide the sidebar when not in use?",
                "type": "boolean",
                "default": False,
            }
        ],
    },
    {
        "key": "agent",
        "title": "Agent settings",
        "help": "Customize how you interact with agents",
        "type": "object",
        "fields": [
            {
                "key": "thoughts",
                "title": "Agent thoughts",
                "help": "Show agent's 'thoughts' in the conversation?",
                "type": "boolean",
            },
            # {
            #     "key": "warn",
            #     "title": "Warning against dangerous commands?",
            #     "help": "Please note that this can produce false positive [i]and[/i] false negatives. If you get a warning, examine the command more closely. But do not assume a command is safe if you get no warning.\n\nThis setting will have no effect if you have given the agent permissions to execute all commands.",
            #     "type": "boolean",
            #     "default": True,
            # },
        ],
    },
    {
        "key": "tools",
        "title": "Tool call settings",
        "help": "Customize how Toad displays agent tool calls",
        "type": "object",
        "fields": [
            {
                "key": "expand",
                "title": "Tool call expand",
                "help": "When should Toad expand tool calls?",
                "type": "choices",
                "default": "fail",
                "choices": [
                    ("Never", "never"),
                    ("Always", "always"),
                    ("Success only", "success"),
                    ("Fail only", "fail"),
                    ("Fail and success", "both"),
                ],
            }
        ],
    },
    {
        "key": "shell",
        "title": "Shell settings",
        "help": "Customize shell interactions.",
        "type": "object",
        "fields": [
            {
                "key": "command",
                "title": "Shell command",
                "type": "string",
                "help": "Command used to launch your shell (on Windows: powershell.exe, pwsh, cmd.exe or Git Bash's bash.exe).\n[bold]Note:[/] Requires restart.",
                "default": "powershell.exe -NoLogo" if sys.platform == "win32" else "/bin/sh",
            },
            {
                "key": "command_start",
                "title": "Startup commands",
                "type": "text",
                "help": "Command(s) to run on shell start.",
                "default": "" if sys.platform == "win32" else 'PS1=""',
            },
            {
                "key": "warn_dangerous",
                "title": "Warn against potentially destructive commands?",
                "help": "If enabled, Toad will highlight potentially destructive commands that may modify the filesystem outside of the project directory.\n\nNote that false positive [i]and[/] false negatives are possible.",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "allow_commands",
                "title": "Allow commands",
                "help": "List of commands (one per line) which should be considered shell commands by default, rather than a part of a prompt.",
                "type": "text",
                "default": "python\ngit\nls\ncat\ncd\nmv\ncp\ntree\nrm\necho\nrmdir\nmkdir\ntouch\nopen\npwd\nnano\nhead\ntail",
            },
            {
                "key": "directory_commands",
                "title": "Directory commands",
                "help": "List of commands (one per line) which accept only a directory as their first argument (used in tab completion).",
                "type": "text",
                "default": "cd\nrmdir",
            },
            {
                "key": "file_commands",
                "title": "File commands",
                "help": "List of commands (one per line) which accept only a non-directory as their first argument (used in tab completion).",
                "type": "text",
                "default": "cat",
            },
        ],
    },
    {
        "key": "diff",
        "title": "Diff view settings",
        "help": "Customize how diffs are displayed.",
        "type": "object",
        "fields": [
            {
                "key": "view",
                "title": "Display preference",
                "default": "auto",
                "type": "choices",
                "choices": [
                    ("Unified", "unified"),
                    ("Split", "split"),
                    ("Best fit", "auto"),
                ],
            },
            {
                "key": "annotations",
                "title": "Show annotations (+/- symbols)?",
                "type": "boolean",
                "default": False,
            },
            {
                "key": "wrap",
                "title": "Wrap code?",
                "help": "If wrapping is disabled you can horizontal scroll with the trackpad or the mouse wheel plus shift.",
                "type": "choices",
                "default": "no-wrap",
                "choices": [
                    ("Don't wrap", "no-wrap"),
                    ("Wrap long lines", "wrap"),
                ],
            },
        ],
    },
    {
        "key": "launcher",
        "title": "Launcher settings",
        "help": "Customize the launcher",
        "type": "object",
        "editable": False,
        "fields": [
            {
                "key": "agents",
                "title": "Agents to show in the launcher",
                "type": "text",
                "default": "claude.com\ngeminicli.com\nopenai.com",
            }
        ],
    },
    {
        "key": "statistics",
        "title": "Data collection",
        "help": "Preferences regarding data collection.",
        "type": "object",
        "fields": [
            {
                "key": "allow_collect",
                "title": "Allow collection of anonymous usage data?",
                "help": "Toad can collect basic usage data (number of installs, OS version, agents used, session length etc). This information is associated with a randomly generated UUID (see it in /about:toad) and contains no personal information.\n\nCollecting this information will help me (Will McGugan) convince big tech to take this project seriously. I would appreciate if you left this on, but it is entirely up to you.",
                "type": "boolean",
                # Íris: opt-in, since it may run on company machines.
                "default": False,
            },
        ],
    },
    {
        "key": "iris",
        "title": "Íris",
        "help": "Aparência do círculo da Íris.",
        "type": "object",
        "fields": [
            {
                "key": "orb_theme",
                "title": "Tema do olho",
                "help": "Arco: anel estilo reator (cores de planejamento e execução abaixo). Sharingan: olho vermelho com 1 tomoe no planejamento, 3 na execução e Mangekyō quando uma skill ou subagente está rodando (ou num modo sem permissões).",
                "type": "choices",
                "default": "arco",
                "choices": [("Arco (reator)", "arco"), ("Sharingan", "sharingan")],
            },
            {
                "key": "elevated_modes",
                "title": "Modos de nível máximo",
                "help": "Palavras, separadas por vírgula, que identificam modos tratados como nível máximo (Mangekyō no tema Sharingan, três cometas no Arco), além das skills e subagentes.",
                "type": "string",
                "default": "bypass, yolo",
            },
            {
                "key": "plan_color",
                "title": "Cor do planejamento",
                "help": "Cor do círculo em modos de planejamento (ex.: #29c7ff, cyan, rgb(41,199,255)).",
                "type": "string",
                "default": "#29c7ff",
            },
            {
                "key": "exec_color",
                "title": "Cor da execução",
                "help": "Cor do círculo nos demais modos (ex.: #ff8a1f, orange).",
                "type": "string",
                "default": "#ff8a1f",
            },
            {
                "key": "attention_color",
                "title": "Cor de atenção",
                "help": "Cor do círculo enquanto o agente espera uma permissão sua.",
                "type": "string",
                "default": "#ffd23f",
            },
            {
                "key": "error_color",
                "title": "Cor de erro",
                "help": "Cor do círculo quando o agente falha.",
                "type": "string",
                "default": "#ff4d5e",
            },
            {
                "key": "agent_colors",
                "title": "Cores por agente",
                "help": "Cor do anel interno por agente, no formato palavra=cor, separado por vírgula. A palavra é procurada no id e no nome do agente.",
                "type": "string",
                "default": "claude=#d97757, codex=#10a37f, openai=#10a37f, gemini=#7b8cff",
            },
            {
                "key": "plan_modes",
                "title": "Modos de planejamento",
                "help": "Palavras, separadas por vírgula, que identificam um modo de planejamento pelo id ou nome do modo do agente.",
                "type": "string",
                "default": "plan, read-only",
            },
            {
                "key": "show_usage",
                "title": "Mostrar uso da assinatura?",
                "help": "Mostra embaixo do círculo quanto dos limites da assinatura (5 horas e semana) já foi usado e quando o de 5 horas volta. Hoje só o Claude informa isso.",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "agents",
                "title": "Agentes na tela inicial",
                "help": "Identidades dos agentes exibidos na tela inicial, separadas por vírgula. Deixe vazio para mostrar todos.",
                "type": "string",
                "default": "claude.com, openai.com, geminicli.com",
            },
        ],
    },
    {
        "key": "voz",
        "title": "Voz",
        "help": "Voz local da Íris (nada sai da sua máquina). Requer o serviço iris-voz instalado.",
        "type": "object",
        "fields": [
            {
                "key": "modo",
                "title": "Modo da voz",
                "help": "Avisos: a Íris fala em momentos definidos (bom dia, troca de modo, executando PowerShell...). Ditado: F9 para falar em vez de digitar. Completa: também lê um resumo das respostas.",
                "type": "choices",
                "default": "desligada",
                "choices": [
                    ("Desligada", "desligada"),
                    ("Só avisos", "avisos"),
                    ("Só ditado (F9)", "ditado"),
                    ("Ditado + avisos", "ditado_avisos"),
                    ("Completa: ditado, avisos e respostas", "completa"),
                ],
            },
            {
                "key": "nome",
                "title": "Seu nome",
                "help": "Usado na saudação (ex.: Bom dia, Ana.). Pode ficar vazio.",
                "type": "string",
                "default": "",
            },
            {
                "key": "frases",
                "title": "Frases por evento",
                "help": 'Uma linha por evento, no formato evento = frase. Deixe a frase vazia para silenciar. Variáveis: {saudacao} {nome} {agente} {modo} {programa} {arquivo} {etapas} {duracao}. Eventos: saudacao, conectado, falha, modo_planejamento, modo_execucao, trabalhando, executando, editando, apagando, movendo, lendo, pesquisando, web, permissao, plano, concluido, erro, tchau.',
                "type": "text",
                "default": 'saudacao = {saudacao}, {nome}.\nconectado = {agente} conectado.\nfalha = Não consegui falar com {agente}.\nmodo_planejamento = Modo de planejamento.\nmodo_execucao = Modo de execução.\ntrabalhando =\nexecutando = Executando {programa}.\neditando = Editando {arquivo}.\napagando = Apagando {arquivo}.\nmovendo = Movendo {arquivo}.\nlendo =\npesquisando =\nweb = Acessando a web.\npermissao = Preciso da sua permissão.\nplano =\nconcluido = Pronto. Terminei em {duracao}.\nerro = Algo deu errado.\ntchau = Até logo.\n',
            },
            {
                "key": "concluido_segundos",
                "title": "Avisar conclusão após (segundos)",
                "help": "Só avisa que terminou se o agente trabalhou pelo menos esse tempo. 0 avisa sempre.",
                "type": "integer",
                "default": 20,
            },
            {
                "key": "resposta_max",
                "title": "Tamanho do resumo falado",
                "help": "No modo Completa, quantos caracteres da resposta ler (código nunca é lido).",
                "type": "integer",
                "default": 350,
            },
            {
                "key": "comandos",
                "title": "Comandos de voz?",
                "help": "Ditado que começa com 'Íris' vira comando da própria Íris (ex.: 'Íris, modo planejamento', 'Íris, abrir o Gemini', 'Íris, ajuda').",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "enviar_ditado",
                "title": "Enviar o ditado automaticamente?",
                "help": "Se desligado, o texto ditado vai para o campo de digitação para você revisar.",
                "type": "boolean",
                "default": False,
            },
            {
                "key": "motor",
                "title": "Motor de fala",
                "help": "Automático usa Kokoro na GPU (mais natural) ou Piper no processador (mais leve).",
                "type": "choices",
                "default": "auto",
                "choices": [
                    ("Automático", "auto"),
                    ("Kokoro (natural, ideal com GPU)", "kokoro"),
                    ("Piper (leve, processador)", "piper"),
                ],
            },
            {
                "key": "voz",
                "title": "Voz do Kokoro",
                "type": "choices",
                "default": "pf_dora",
                "choices": [
                    ("Dora (feminina)", "pf_dora"),
                    ("Alex (masculina)", "pm_alex"),
                    ("Santa (masculina)", "pm_santa"),
                ],
            },
            {
                "key": "velocidade",
                "title": "Velocidade da fala",
                "help": "1.0 é o normal; 1.2 é 20% mais rápido.",
                "type": "string",
                "default": "1.0",
            },
            {
                "key": "ditado_modelo",
                "title": "Modelo do ditado",
                "help": "Automático usa large-v3-turbo na GPU ou small no processador.",
                "type": "choices",
                "default": "auto",
                "choices": [
                    ("Automático", "auto"),
                    ("large-v3-turbo (GPU)", "large-v3-turbo"),
                    ("small (processador)", "small"),
                    ("base (mais leve)", "base"),
                ],
            },
            {
                "key": "somente_cpu",
                "title": "Usar só o processador?",
                "help": "Ignora a GPU mesmo se existir.",
                "type": "boolean",
                "default": False,
            },
            {
                "key": "comando",
                "title": "Comando do serviço de voz",
                "type": "string",
                "default": "iris-voz",
            },
        ],
    },
]
